### ISSUE TITLE
Running Ansiblespecs on Centos 6.x platform

### ISSUE THREAD

**Issue by wilkko** [neillturner/ansible_repo#1]
How to run "ansiblespecs" against default Centos-6.x platform? I get errors for the Ruby version being too old.

My .kitchen.yml:

```
  driver:
    name: vagrant

  provisioner:
    hosts: test-kitchen
    name: ansible_playbook
    playbook: test/integration/default.yml
    require_chef_for_busser: false
    require_ruby_for_busser: true
    ansible_verbose: true
    ansible_verbosity: 3

    - name: centos-6.7

  verifier:
    ruby_bindir: '/usr/bin'

  suites:
    - name: ansible-roles
```

 is failing on kitchen verify :

```
-----> Starting Kitchen (v1.4.2)
-----> Setting up <ansible-roles-centos-67>...
       Finished setting up <ansible-roles-centos-67> (0m0.00s).
-----> Verifying <ansible-roles-centos-67>...
       Preparing files for transfer
-----> Busser installation detected (busser)
       Installing Busser plugins: busser-ansiblespec
       Plugin ansiblespec already installed
       Removing /tmp/verifier/suites/ansiblespec
       Transferring files to <ansible-roles-centos-67>
-----> Running ansiblespec test suite
-----> Installing Serverspec..
       /opt/rh/ruby193/root/usr/share/rubygems/rubygems/installer.rb:388:in `ensure_required_ruby_version_met': net-ssh requires Ruby version >= 2.0. (Gem::InstallError)
        from /opt/rh/ruby193/root/usr/share/rubygems/rubygems/installer.rb:156:in `install'
        from /opt/rh/ruby193/root/usr/share/rubygems/rubygems/dependency_installer.rb:297:in `block in install'
        from /opt/rh/ruby193/root/usr/share/rubygems/rubygems/dependency_installer.rb:270:in `each'
        from /opt/rh/ruby193/root/usr/share/rubygems/rubygems/dependency_installer.rb:270:in `each_with_index'
        from /opt/rh/ruby193/root/usr/share/rubygems/rubygems/dependency_installer.rb:270:in `install'
        from /tmp/verifier/gems/gems/busser-0.7.1/lib/busser/rubygems.rb:44:in `install_gem'
        from /tmp/verifier/gems/gems/busser-0.7.1/lib/busser/helpers.rb:57:in `install_gem'
        from /tmp/verifier/gems/gems/busser-ansiblespec-0.5.9/lib/busser/runner_plugin/ansiblespec.rb:60:in `install_serverspec'
        from /tmp/verifier/gems/gems/busser-ansiblespec-0.5.9/lib/busser/runner_plugin/ansiblespec.rb:33:in `test'
        from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/command.rb:27:in `run'
        from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:126:in `invoke_command'
        from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:133:in `block in invoke_all'
        from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:133:in `each'
        from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:133:in `map'
        from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:133:in `invoke_all'
        from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/group.rb:232:in `dispatch'
        from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:115:in `invoke'
        from /tmp/verifier/gems/gems/busser-0.7.1/lib/busser/command/test.rb:43:in `block in perform'
        from /tmp/verifier/gems/gems/busser-0.7.1/lib/busser/command/test.rb:35:in `each'
        from /tmp/verifier/gems/gems/busser-0.7.1/lib/busser/command/test.rb:35:in `perform'
        from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/command.rb:27:in `run'
        from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:126:in `invoke_command'
        from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:133:in `block in invoke_all'
        from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:133:in `each'
        from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:133:in `map'
        from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:133:in `invoke_all'
        from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/group.rb:232:in `dispatch'
        from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:115:in `invoke'
        from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor.rb:40:in `block in register'
        from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/command.rb:27:in `run'
        from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:126:in `invoke_command'
        from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor.rb:359:in `dispatch'
        from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/base.rb:440:in `start'
        from /tmp/verifier/gems/gems/busser-0.7.1/bin/busser:8:in `<top (required)>'
        from /tmp/verifier/gems/bin/busser:23:in `load'
        from /tmp/verifier/gems/bin/busser:23:in `<main>'
```

**Comment by neillturner** [comment]
try with the new version of busser-ansible  works via ssh now

**Comment by neillturner** [comment]
this repo is a demo for centos 7 so closing. 
should work fine on centos 6 if: .kitchen.yml
    require_chef_for_busser: true
    require_ruby_for_busser: false
